"""Keep the existing full-page PDF renderer, adapted to the V5 summary and state."""
from pathlib import Path
p=Path('trip-export.js');s=p.read_text()
if "toolbar.dataset.v5" in s: raise SystemExit(0)
s=s.replace("document.querySelector('.app-shell').append(toolbar);", "toolbar.dataset.v5='true';\n  document.querySelector('#v5Summary').insertBefore(toolbar,document.querySelector('#v5ReportFields'));")
s=s.replace("const ready=$('results').classList.contains('show')&&!$('calculateBtn').disabled;", "const ready=window.TripV5?.ready()||false;")
s=s.replace("exportButton.disabled=busy||!ready;printButton.disabled=busy||!ready;", "exportButton.disabled=busy||document.body.dataset.pdfBusy==='true'||!ready;printButton.disabled=exportButton.disabled;")
s=s.replace("if(!ready&&!busy){status.textContent='';downloadLink.hidden=true;}","if(!ready&&!busy){status.textContent='';downloadLink.hidden=true;}")
s=s.replace("  syncExport();\n  printButton", "  document.addEventListener('trip:calculated',syncExport);\n  document.addEventListener('trip:export-busy',syncExport);\n  document.addEventListener('trip:invalidate',()=>{downloadLink.hidden=true;if(!busy)status.textContent='';syncExport();});\n  syncExport();\n  printButton")
s=s.replace("  async function makeSnapshot(){","  async function makeSnapshot(report){")
s=s.replace("document.querySelectorAll('style').forEach(style=>doc.head.append(style.cloneNode(true)));", "Array.from(document.styleSheets).forEach(sheet=>{try{const copy=doc.createElement('style');copy.textContent=Array.from(sheet.cssRules).map(r=>r.cssText).join('\\n');doc.head.append(copy);}catch{}});")
s=s.replace("const source=document.querySelector('.app-shell'),clone=source.cloneNode(true);", "const source=document.querySelector('.app-shell'),clone=source.cloneNode(true);\n      clone.querySelectorAll('.no-print,.export-actions,.summary-state,.paragraph-help').forEach(node=>node.remove());\n      clone.querySelectorAll('details').forEach(node=>node.open=true);\n      const adjustments=clone.querySelector('#v5Advanced');\n      if(adjustments){const entries=Object.entries(report.snapshot.adjustments);if(!entries.length)adjustments.remove();else{adjustments.replaceChildren();const title=doc.createElement('strong');title.textContent='逐日供餐調整';adjustments.append(title);entries.sort().forEach(([key,value])=>{const row=doc.createElement('p');row.className='pdf-adjustment';row.textContent=key.slice(0,10)+' '+({B:'早餐',L:'午餐',D:'晚餐'}[key.slice(-1)])+'：'+({hotel:'飯店供餐',expo:'展場供餐',company:'公司／他人供餐',self:'未供餐'}[value]);adjustments.append(row);});}}")
s=s.replace("clone.querySelectorAll('input').forEach(input=>{", "clone.querySelectorAll('input,textarea').forEach(input=>{")
s=s.replace("input.closest('.switch').replaceWith(value);", "(input.closest('.switch')||input).replaceWith(value);")
s=s.replace("clone.querySelector('.hero').append(meta);", "clone.querySelector('.hero').append(meta);\n      if(report.meta.name||report.meta.department||report.meta.purpose){const info=doc.createElement('p');info.className='pdf-meta';info.textContent=[report.meta.name&&'姓名：'+report.meta.name,report.meta.department&&'部門：'+report.meta.department,report.meta.purpose&&'事由：'+report.meta.purpose].filter(Boolean).join('｜');clone.querySelector('.hero').append(info);}")
s=s.replace(".basis,.summary-card')).map", ".basis,.summary-card,.pdf-adjustment')).map")
s=s.replace("if(busy||exportButton.disabled)return;", "if(busy||exportButton.disabled||document.body.dataset.pdfBusy==='true')return;\n    const report=window.TripV5.getReport();if(!report)return;\n    document.body.dataset.pdfBusy='true';document.dispatchEvent(new Event('trip:export-busy'));")
s=s.replace("const render=await loadRenderer();\n      snapshot=await makeSnapshot();", "snapshot=await makeSnapshot(report);\n      const render=await loadRenderer();")
s=s.replace("const place=$('summaryPlace').textContent", "const place=(report.country+'・'+report.city)")
s=s.replace("${$('arrDate').value.replaceAll('/','-')}_${$('depDate').value.replaceAll('/','-')}", "${report.arrDate}_${report.depDate}")
s=s.replace("busy=false;exportButton.removeAttribute", "busy=false;document.body.dataset.pdfBusy='false';document.dispatchEvent(new Event('trip:export-busy'));exportButton.removeAttribute")
s=s.replace(".hero-actions,.desktop-actions,.export-actions,.result-toggle", ".no-print,.summary-state,.hero-actions,.desktop-actions,.export-actions,.result-toggle")
s=s.replace(".pdf-value{min-height", ".pdf-adjustment{font-size:12px;line-height:1.6;margin:6px 0;}.summary-trip{font-size:13px;}\n    .pdf-value{min-height")
p.write_text(s)
